In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
plt.rcParams['figure.figsize'] = 16,9
from sklearn.linear_model import LinearRegression

In [3]:
data = pd.read_csv('D:\\Users\\Minerva\\Programming\\Udemy\\The Data Science Course 2019 Complete Data Science Bootcamp\\34. Advanced Statistical Methods - Linear Regression with sklearn\\2 Multiple linear regression.csv')

In [4]:
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [5]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

In [6]:
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']
reg = LinearRegression()
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [7]:
reg.coef_

array([ 0.00165354, -0.00826982])

Calculating R Squared

In [8]:
reg.score(x,y)

0.40668119528142815

In [9]:
# Adjusted R Squared not as easy as stats model

### Formula for Adjusted R^2
$R^2_{adj.} = 1 - (1-R^2)*\frac{n-1}{n-p-1}$

In [10]:
# Where n = # of observations
#  and p = # of predictors

In [11]:
x.shape

(84, 2)

In [14]:
r2 = reg.score(x,y)
n = x.shape[0]
p = x.shape[1]
r2adj = 1-(1-r2)*((n-1)/(n-p-1))
r2adj

0.39203134825134

In [ ]:
# Lower adjusted r^2 indicates that on of our predictors is irrelivent

# Feature Selection

In [16]:
from sklearn.feature_selection import f_regression
f_regression(x,y)
# F stats first, P values in second array element

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [17]:
pvals = f_regression(x,y)[1]
pvals

array([7.19951844e-11, 6.76291372e-01])

In [18]:
pvals.round(3)

array([0.   , 0.676])

In [19]:
# SAT is usefull, while rand 123 is useless
# F regression can be simple and less helpful for more complicated problems

# Creating Summary Table

In [20]:
reg_summary = pd.DataFrame(data=x.columns.values, columns=['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [22]:
reg_summary['Coefficients'] = reg.coef_
reg_summary['pvals'] = pvals.round(3)
reg_summary

Features  Coefficients  pvals
0         SAT      0.001654  0.000
1  Rand 1,2,3     -0.008270  0.676

# Standardization - Feature Scaling
$\frac{x-mu}{sigma}$
where x = original varialbe
mu = mean of x
sigma = standard deviation

In [ ]:
# Example Stock trading volume

In [23]:
from sklearn.preprocessing import StandardScaler

In [24]:
scaler = StandardScaler()
scaler.fit(x)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [25]:
x_scaled = scaler.transform(x)
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

# Regression with Scaled Features

In [27]:
reg = LinearRegression()
reg.fit(x_scaled,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [28]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [29]:
reg.intercept_

3.330238095238095

# Summary Table

In [30]:
reg_summary = pd.DataFrame([['Intercept'],['SAT'],['Rand 1,2,3']], columns=['Features'])
reg_summary['Weights'] = reg.intercept_, reg.coef_[0], reg.coef_[1]

In [31]:
reg_summary

Features   Weights
0   Intercept  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

In [32]:
# Weights == coefficients
# Intercept == bias