In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
plt.rcParams['figure.figsize'] = 16,9
from sklearn.linear_model import LinearRegression
data = pd.read_csv('D:\\Users\\Minerva\\Programming\\Udemy\\The Data Science Course 2019 Complete Data Science Bootcamp\\34. Advanced Statistical Methods - Linear Regression with sklearn\\2 Multiple linear regression.csv')

In [3]:
from sklearn.preprocessing import StandardScaler
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']

scaler = StandardScaler()
scaler.fit(x)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [4]:
x_scaled = scaler.transform(x)
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

# Predictions w/ Standardized coefficients (weights)

In [5]:
new_data = pd.DataFrame(data=[[1700,2],[1800,1]], columns=['SAT','Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [6]:
reg = LinearRegression()
reg.fit(x_scaled,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [7]:
reg.predict(new_data)

array([295.39979563, 312.58821497])

In [8]:
# new data wasn't standardized
new_data_scaled = scaler.transform(new_data)
new_data_scaled

array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [9]:
reg.predict(new_data_scaled)

array([3.09051403, 3.26413803])

# What if we removed rand 1,2,3?

In [12]:
reg_simple = LinearRegression()
x_simple = x_scaled[:,0].reshape(-1,1)
reg_simple.fit(x_simple,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [13]:
reg_simple.predict(new_data_scaled[:,0].reshape(-1,1))

array([3.08970998, 3.25527879])

In [ ]:
# doesn't really change, feature scaling made rand irrelivant

# Training and Test Splitting

In [14]:
from sklearn.model_selection import train_test_split

In [23]:
a = np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [24]:
b = np.arange(501,601)

In [20]:
train_test_split(a)

[array([ 54,  10,  44,  60,  53,  97,  26,   7,  24,  79,  91,  86,  84,
         92,  46,  68,  48,  77,  35,  34,  12,  32,  15,   3,  96,  73,
         81,  43,  13,  75,  52,  18,  20,  72,  88,  29,   4,  21,  89,
         17,   9,  80,  19,  58,  90,  27,  62,  87,  67,   2,  47,  76,
         33,  40,  37,  28,   8,  99,  93,  94,  95,  74,  38,  39,  23,
          1,  11,  57,   6, 100,   5,  51,  69,  64,  98,  65,  36,  56,
         71,  78]),
 array([50, 30, 31, 66, 70, 83, 14, 45, 61, 25, 82, 55, 85, 41, 59, 16, 49,
        22, 63, 42])]

In [25]:
a_train, a_test = train_test_split(a, test_size=0.2)

In [26]:
a_train.shape, a_test.shape

((80,), (20,))

In [28]:
a_train, a_test, b_train, b_test = train_test_split(a,b, test_size=0.2, random_state=24)

In [29]:
a_train.shape, a_test.shape

((80,), (20,))

In [30]:
b_train

array([591, 525, 551, 530, 555, 545, 579, 554, 553, 517, 550, 510, 570,
       524, 575, 539, 509, 560, 567, 573, 540, 552, 531, 590, 600, 523,
       533, 578, 537, 544, 503, 522, 569, 597, 582, 564, 543, 520, 506,
       586, 546, 557, 542, 563, 511, 592, 599, 593, 528, 598, 584, 548,
       566, 547, 507, 571, 556, 561, 594, 534, 513, 501, 529, 536, 526,
       508, 519, 574, 516, 512, 583, 505, 580, 502, 596, 518, 588, 565,
       504, 535])

In [31]:
b_test

array([527, 532, 538, 587, 577, 515, 589, 549, 572, 568, 514, 585, 559,
       541, 576, 595, 521, 558, 562, 581])

In [32]:
a_test

array([27, 32, 38, 87, 77, 15, 89, 49, 72, 68, 14, 85, 59, 41, 76, 95, 21,
       58, 62, 81])